require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MyFyp2' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

  pod 'RNSoundPlayer', :path => '../node_modules/react-native-sound-player'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'MyFyp2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'MyFyp2-tvOS' do
  # Pods for MyFyp2-tvOS

  target 'MyFyp2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
